travis:
  secure:
    BINSTAR_TOKEN: f9IbAmUWxrwyijFXPfes1fcWhXN+ZHqqA9jBLQ5kdhFcV2901ol9Yk/HJ8lE02j+t+XFjrsLs8qk8oQ0o4jOb+7bR87gkv/iCkQAEI7nZgMHXq//jBZYvc+ByqJlzIpWNz041JQnGDw7GdcQnyAJUva7dGHIyAseOhc2mW7i8Rj7D706LfVM7eDPhIBkrStUHiD9xN//p1+xefpIsOmsYoJSW9GRnzsp5h334eYMet219lkrdL/qMaNtQpaiTbvOMurnsvXH7rE6lW7LY9d/UkTIoIACINWddSR095/65ViaN7kbadY31AlqqkqwXT+hKm2xqi3VV0atXj4XpB42VCxW5drgkbmucrTlNYsEI/dq0djaxkCpRPmIaGI0aB//LUaPtm82KL7CU6Pm1WVm9GEZQ3tJ99niO5Ma00sACOic5y280UkzHmkFGyDlCmbbFroHnS1LUTQ1GN2vYTmGRy0lCaxkX9RBS953JwhOp4lo13QbJJkUasYZEDaVMURoB4AajjUIl8w4rhe7Nnv2reN/FveJOF3W0rIhftaine1Uz5zTB8AtnbIDZWmEFGK3inEvUCBaJ3p1/v7ERZ1ExJFVZgs7jaqMAfLWBmXwxpFCeZmEOthBt5OyBUv3o478rm9Zr0pulBQCV6YojDsjIn2V7UgFO1IM8qSVAlZboDo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
